"""position_tbl_avg_price

Revision ID: 0bcc3e69d4c0
Revises: 931334c6840f
Create Date: 2024-10-30 21:17:00.015640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bcc3e69d4c0'
down_revision: Union[str, None] = '931334c6840f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('avg_price', sa.DECIMAL(precision=20, scale=8), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'avg_price')
    # ### end Alembic commands ###
