"""line

Revision ID: 14731eb1d6b6
Revises: a21b96dbd84b
Create Date: 2024-11-28 00:03:38.515236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14731eb1d6b6'
down_revision: Union[str, None] = 'a21b96dbd84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lines', sa.Column('locked', sa.BOOLEAN(), nullable=True))
    op.add_column('lines', sa.Column('style', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lines', 'style')
    op.drop_column('lines', 'locked')
    # ### end Alembic commands ###
