"""add

Revision ID: 24c9b58d16d2
Revises: 4f19b9a186ce
Create Date: 2024-09-30 00:48:10.517825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c9b58d16d2'
down_revision: Union[str, None] = '4f19b9a186ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('line_type', sa.String(), nullable=False),
    sa.Column('x0', sa.TIMESTAMP(), nullable=False),
    sa.Column('y0', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('x1', sa.TIMESTAMP(), nullable=False),
    sa.Column('y1', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lines_created_at'), 'lines', ['created_at'], unique=False)
    op.create_index(op.f('ix_lines_id'), 'lines', ['id'], unique=False)
    op.create_index(op.f('ix_lines_symbol_id'), 'lines', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_lines_user_id'), 'lines', ['user_id'], unique=False)
    op.create_index(op.f('ix_lines_x0'), 'lines', ['x0'], unique=False)
    op.create_index(op.f('ix_lines_x1'), 'lines', ['x1'], unique=False)
    op.create_index(op.f('ix_lines_y0'), 'lines', ['y0'], unique=False)
    op.create_index(op.f('ix_lines_y1'), 'lines', ['y1'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lines_y1'), table_name='lines')
    op.drop_index(op.f('ix_lines_y0'), table_name='lines')
    op.drop_index(op.f('ix_lines_x1'), table_name='lines')
    op.drop_index(op.f('ix_lines_x0'), table_name='lines')
    op.drop_index(op.f('ix_lines_user_id'), table_name='lines')
    op.drop_index(op.f('ix_lines_symbol_id'), table_name='lines')
    op.drop_index(op.f('ix_lines_id'), table_name='lines')
    op.drop_index(op.f('ix_lines_created_at'), table_name='lines')
    op.drop_table('lines')
    # ### end Alembic commands ###
