"""remove

Revision ID: 44a25d074b97
Revises: ad483a3af524
Create Date: 2024-11-23 12:37:39.845661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a25d074b97'
down_revision: Union[str, None] = 'ad483a3af524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_broker_id', table_name='orders')
    op.drop_constraint('orders_broker_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'broker_id')
    op.drop_index('ix_positions_broker_id', table_name='positions')
    op.drop_constraint('positions_broker_id_fkey', 'positions', type_='foreignkey')
    op.drop_column('positions', 'broker_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('broker_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('positions_broker_id_fkey', 'positions', 'brokers', ['broker_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_positions_broker_id', 'positions', ['broker_id'], unique=False)
    op.add_column('orders', sa.Column('broker_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_broker_id_fkey', 'orders', 'brokers', ['broker_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_orders_broker_id', 'orders', ['broker_id'], unique=False)
    # ### end Alembic commands ###
