"""apiv2

Revision ID: 4f19b9a186ce
Revises: 9c2c2eb5c185
Create Date: 2024-05-13 23:36:49.619158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f19b9a186ce'
down_revision: Union[str, None] = '9c2c2eb5c185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
