"""position_tbl_entry_price

Revision ID: 5bedc57f1b58
Revises: 0bcc3e69d4c0
Create Date: 2024-10-30 21:41:10.251662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bedc57f1b58'
down_revision: Union[str, None] = '0bcc3e69d4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('entry_price', sa.DECIMAL(precision=20, scale=8), nullable=False))
    op.drop_column('positions', 'avg_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('avg_price', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True))
    op.drop_column('positions', 'entry_price')
    # ### end Alembic commands ###
