"""chart_settings

Revision ID: 606b31db9652
Revises: b3b0844c69b9
Create Date: 2024-11-04 20:54:31.247337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '606b31db9652'
down_revision: Union[str, None] = 'b3b0844c69b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol_id', name='_chart_settings_user_id_symbol_id_uc')
    )
    op.create_index(op.f('ix_chart_settings_id'), 'chart_settings', ['id'], unique=False)
    op.add_column('users', sa.Column('last_symbol_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'symbols', ['last_symbol_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'last_symbol_id')
    op.drop_index(op.f('ix_chart_settings_id'), table_name='chart_settings')
    op.drop_table('chart_settings')
    # ### end Alembic commands ###
