"""line

Revision ID: 6415c5b2dd6b
Revises: a5df7452a8fb
Create Date: 2024-10-06 13:51:35.245207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6415c5b2dd6b'
down_revision: Union[str, None] = 'a5df7452a8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('line_id', sa.Integer(), nullable=True))
    op.alter_column('alerts', 'price',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
    op.create_index(op.f('ix_alerts_line_id'), 'alerts', ['line_id'], unique=False)
    op.create_foreign_key(None, 'alerts', 'lines', ['line_id'], ['id'], ondelete='CASCADE')
    op.alter_column('lines', 'x1',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('lines', 'y1',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lines', 'y1',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
    op.alter_column('lines', 'x1',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_line_id'), table_name='alerts')
    op.alter_column('alerts', 'price',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
    op.drop_column('alerts', 'line_id')
    # ### end Alembic commands ###
