"""symbol

Revision ID: 869dd0e185c6
Revises: f0f83494f4e4
Create Date: 2024-10-12 17:57:18.227076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '869dd0e185c6'
down_revision: Union[str, None] = 'f0f83494f4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbols', sa.Column('last_update_time', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbols', 'last_update_time')
    # ### end Alembic commands ###
