"""position

Revision ID: 9d02da3efe1a
Revises: a5c27413022b
Create Date: 2024-10-22 21:35:40.377864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d02da3efe1a'
down_revision: Union[str, None] = 'a5c27413022b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('size', sa.DECIMAL(precision=20, scale=8), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'size')
    # ### end Alembic commands ###
