"""add

Revision ID: a21b96dbd84b
Revises: d19a33219870
Create Date: 2024-11-27 00:43:48.021238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a21b96dbd84b'
down_revision: Union[str, None] = 'd19a33219870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('klines',
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('start', sa.TIMESTAMP(), nullable=False),
    sa.Column('open', sa.DECIMAL(), nullable=False),
    sa.Column('high', sa.DECIMAL(), nullable=False),
    sa.Column('low', sa.DECIMAL(), nullable=False),
    sa.Column('close', sa.DECIMAL(), nullable=False),
    sa.PrimaryKeyConstraint('symbol_id', 'interval', 'start')
    )
    op.create_index(op.f('ix_klines_close'), 'klines', ['close'], unique=False)
    op.create_index(op.f('ix_klines_high'), 'klines', ['high'], unique=False)
    op.create_index(op.f('ix_klines_interval'), 'klines', ['interval'], unique=False)
    op.create_index(op.f('ix_klines_low'), 'klines', ['low'], unique=False)
    op.create_index(op.f('ix_klines_open'), 'klines', ['open'], unique=False)
    op.create_index(op.f('ix_klines_start'), 'klines', ['start'], unique=False)
    op.create_index(op.f('ix_klines_symbol_id'), 'klines', ['symbol_id'], unique=False)
    op.add_column('symbols', sa.Column('klines_max_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbols', 'klines_max_count')
    op.drop_index(op.f('ix_klines_symbol_id'), table_name='klines')
    op.drop_index(op.f('ix_klines_start'), table_name='klines')
    op.drop_index(op.f('ix_klines_open'), table_name='klines')
    op.drop_index(op.f('ix_klines_low'), table_name='klines')
    op.drop_index(op.f('ix_klines_interval'), table_name='klines')
    op.drop_index(op.f('ix_klines_high'), table_name='klines')
    op.drop_index(op.f('ix_klines_close'), table_name='klines')
    op.drop_table('klines')
    # ### end Alembic commands ###
