"""symbols

Revision ID: a59334f92dc4
Revises: b8cd73174eef
Create Date: 2024-11-18 18:46:33.944284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59334f92dc4'
down_revision: Union[str, None] = 'b8cd73174eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbols', sa.Column('active_wss', sa.BOOLEAN(), nullable=True))
    op.add_column('symbols', sa.Column('contract_type', sa.String(), nullable=True))
    op.add_column('symbols', sa.Column('status', sa.String(), nullable=True))
    op.add_column('symbols', sa.Column('base_coin', sa.String(), nullable=True))
    op.add_column('symbols', sa.Column('quote_coin', sa.String(), nullable=True))
    op.add_column('symbols', sa.Column('launch_time', sa.TIMESTAMP(), nullable=True))
    op.add_column('symbols', sa.Column('delivery_time', sa.TIMESTAMP(), nullable=True))
    op.add_column('symbols', sa.Column('delivery_fee_rate', sa.DECIMAL(), nullable=True))
    op.add_column('symbols', sa.Column('price_scale', sa.DECIMAL(), nullable=True))
    op.add_column('symbols', sa.Column('min_leverage', sa.DECIMAL(), nullable=True))
    op.add_column('symbols', sa.Column('max_leverage', sa.DECIMAL(), nullable=True))
    op.add_column('symbols', sa.Column('leverage_step', sa.DECIMAL(), nullable=True))
    op.add_column('symbols', sa.Column('min_price', sa.DECIMAL(), nullable=True))
    op.add_column('symbols', sa.Column('max_price', sa.DECIMAL(), nullable=True))
    op.add_column('symbols', sa.Column('tick_size', sa.DECIMAL(), nullable=True))
    op.add_column('symbols', sa.Column('max_order_qty', sa.DECIMAL(), nullable=True))
    op.add_column('symbols', sa.Column('max_mkt_order_qty', sa.DECIMAL(), nullable=True))
    op.add_column('symbols', sa.Column('min_order_qty', sa.DECIMAL(), nullable=True))
    op.add_column('symbols', sa.Column('qty_step', sa.DECIMAL(), nullable=True))
    op.add_column('symbols', sa.Column('post_only_max_order_qty', sa.DECIMAL(), nullable=True))
    op.add_column('symbols', sa.Column('min_notional_value', sa.DECIMAL(), nullable=True))
    op.add_column('symbols', sa.Column('unified_margin_trade', sa.BOOLEAN(), nullable=True))
    op.add_column('symbols', sa.Column('funding_interval', sa.Integer(), nullable=True))
    op.add_column('symbols', sa.Column('settle_coin', sa.String(), nullable=True))
    op.add_column('symbols', sa.Column('copy_trading', sa.String(), nullable=True))
    op.add_column('symbols', sa.Column('upper_funding_rate', sa.DECIMAL(), nullable=True))
    op.add_column('symbols', sa.Column('lower_funding_rate', sa.DECIMAL(), nullable=True))
    op.add_column('symbols', sa.Column('taker_fee_rate', sa.DECIMAL(), nullable=True))
    op.add_column('symbols', sa.Column('maker_fee_rate', sa.DECIMAL(), nullable=True))
    op.create_index(op.f('ix_symbols_base_coin'), 'symbols', ['base_coin'], unique=False)
    op.create_index(op.f('ix_symbols_contract_type'), 'symbols', ['contract_type'], unique=False)
    op.create_index(op.f('ix_symbols_quote_coin'), 'symbols', ['quote_coin'], unique=False)
    op.create_index(op.f('ix_symbols_status'), 'symbols', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbols_status'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_quote_coin'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_contract_type'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_base_coin'), table_name='symbols')
    op.drop_column('symbols', 'maker_fee_rate')
    op.drop_column('symbols', 'taker_fee_rate')
    op.drop_column('symbols', 'lower_funding_rate')
    op.drop_column('symbols', 'upper_funding_rate')
    op.drop_column('symbols', 'copy_trading')
    op.drop_column('symbols', 'settle_coin')
    op.drop_column('symbols', 'funding_interval')
    op.drop_column('symbols', 'unified_margin_trade')
    op.drop_column('symbols', 'min_notional_value')
    op.drop_column('symbols', 'post_only_max_order_qty')
    op.drop_column('symbols', 'qty_step')
    op.drop_column('symbols', 'min_order_qty')
    op.drop_column('symbols', 'max_mkt_order_qty')
    op.drop_column('symbols', 'max_order_qty')
    op.drop_column('symbols', 'tick_size')
    op.drop_column('symbols', 'max_price')
    op.drop_column('symbols', 'min_price')
    op.drop_column('symbols', 'leverage_step')
    op.drop_column('symbols', 'max_leverage')
    op.drop_column('symbols', 'min_leverage')
    op.drop_column('symbols', 'price_scale')
    op.drop_column('symbols', 'delivery_fee_rate')
    op.drop_column('symbols', 'delivery_time')
    op.drop_column('symbols', 'launch_time')
    op.drop_column('symbols', 'quote_coin')
    op.drop_column('symbols', 'base_coin')
    op.drop_column('symbols', 'status')
    op.drop_column('symbols', 'contract_type')
    op.drop_column('symbols', 'active_wss')
    # ### end Alembic commands ###
