"""add

Revision ID: a5c27413022b
Revises: 869dd0e185c6
Create Date: 2024-10-22 02:26:02.929776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c27413022b'
down_revision: Union[str, None] = '869dd0e185c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('position_value', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('entry_price', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('mark_price', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('leverage', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('position_balance', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('liq_price', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('take_profit', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('stop_Loss', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('unrealised_pnl', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('cur_realised_pnl', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('cum_realised_pnl', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('position_status', sa.String(), nullable=False),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_broker_id'), 'positions', ['broker_id'], unique=False)
    op.create_index(op.f('ix_positions_created_time'), 'positions', ['created_time'], unique=False)
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index(op.f('ix_positions_position_status'), 'positions', ['position_status'], unique=False)
    op.create_index(op.f('ix_positions_side'), 'positions', ['side'], unique=False)
    op.create_index(op.f('ix_positions_symbol_id'), 'positions', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_positions_updated_time'), 'positions', ['updated_time'], unique=False)
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    op.create_index(op.f('ix_orders_broker_id'), 'orders', ['broker_id'], unique=False)
    op.create_index(op.f('ix_orders_symbol_id'), 'orders', ['symbol_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_symbol_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_id'), table_name='orders')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_updated_time'), table_name='positions')
    op.drop_index(op.f('ix_positions_symbol_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_side'), table_name='positions')
    op.drop_index(op.f('ix_positions_position_status'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_created_time'), table_name='positions')
    op.drop_index(op.f('ix_positions_broker_id'), table_name='positions')
    op.drop_table('positions')
    # ### end Alembic commands ###
