"""add

Revision ID: a5df7452a8fb
Revises: 24c9b58d16d2
Create Date: 2024-10-02 17:45:00.362061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5df7452a8fb'
down_revision: Union[str, None] = '24c9b58d16d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        INSERT INTO brokers (name)
        VALUES 
            ('Bybit-spot'),
            ('Bybit_perpetual'),
            ('Bybit-inverse');
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DROP FROM brokers
        WHERE 
            name = 'Bybit-spot'
            OR name = 'Bybit_perpetual'
            OR name = 'Bybit-inverse';
    """)
    # ### end Alembic commands ###
