"""symbols

Revision ID: ad483a3af524
Revises: a59334f92dc4
Create Date: 2024-11-19 23:15:18.575918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad483a3af524'
down_revision: Union[str, None] = 'a59334f92dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart_settings', sa.Column('taker_fee_rate', sa.DECIMAL(), nullable=True))
    op.add_column('chart_settings', sa.Column('maker_fee_rate', sa.DECIMAL(), nullable=True))
    op.drop_column('symbols', 'maker_fee_rate')
    op.drop_column('symbols', 'taker_fee_rate')
    op.drop_column('symbols', 'post_only_max_order_qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbols', sa.Column('post_only_max_order_qty', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('symbols', sa.Column('taker_fee_rate', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('symbols', sa.Column('maker_fee_rate', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('chart_settings', 'maker_fee_rate')
    op.drop_column('chart_settings', 'taker_fee_rate')
    # ### end Alembic commands ###
