"""position_tbl_sc

Revision ID: b3b0844c69b9
Revises: 5bedc57f1b58
Create Date: 2024-10-30 22:05:55.040121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b0844c69b9'
down_revision: Union[str, None] = '5bedc57f1b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('stop_loss', sa.DECIMAL(precision=20, scale=8), nullable=True))
    op.alter_column('positions', 'entry_price',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
    op.drop_column('positions', 'stop_Loss')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('stop_Loss', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True))
    op.alter_column('positions', 'entry_price',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
    op.drop_column('positions', 'stop_loss')
    # ### end Alembic commands ###
