"""add_brokers

Revision ID: b69f743e110e
Revises: acd0ab0c82c1
Create Date: 2023-12-09 20:26:23.131412

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b69f743e110e'
down_revision: Union[str, None] = 'acd0ab0c82c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        INSERT INTO brokers (name)
        VALUES 
            ('Binance-spot'),
            ('Binance-UM-Futures'),
            ('Binance-CM-Futures');
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DROP FROM brokers
        WHERE 
            name = 'Binance-spot'
            OR name = 'Binance-UM-Futures'
            OR name = 'Binance-CM-Futures';
    """)
    # ### end Alembic commands ###
