"""family_group

Revision ID: cd39becf60bc
Revises: 9632489df213
Create Date: 2024-01-16 16:10:45.522944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd39becf60bc'
down_revision: Union[str, None] = '9632489df213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('family_group', sa.String(), nullable=True))
    op.add_column('users', sa.Column('family_leader', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['family_leader'], ['id'])
    op.alter_column('wallet_transactions', 'amountBTC',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
    op.alter_column('wallet_transactions', 'amountUSD',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=True)
    op.alter_column('wallet_transactions', 'amountRUB',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=True)
    op.alter_column('wallet_transactions', 'amountARS',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_transactions', 'amountARS',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=False)
    op.alter_column('wallet_transactions', 'amountRUB',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=False)
    op.alter_column('wallet_transactions', 'amountUSD',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=False)
    op.alter_column('wallet_transactions', 'amountBTC',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
    op.drop_constraint(None, 'users', type_='foreignkey') # type: ignore
    op.drop_column('users', 'family_leader')
    op.drop_column('users', 'family_group')
    # ### end Alembic commands ###
