"""fix

Revision ID: d19a33219870
Revises: 44a25d074b97
Create Date: 2024-11-23 13:54:22.785853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19a33219870'
down_revision: Union[str, None] = '44a25d074b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'create_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'create_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
