"""orders

Revision ID: f0f83494f4e4
Revises: 6415c5b2dd6b
Create Date: 2024-10-11 12:10:52.892344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f83494f4e4'
down_revision: Union[str, None] = '6415c5b2dd6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('broker_order_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('qty', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=False),
    sa.Column('create_type', sa.String(), nullable=False),
    sa.Column('cancel_type', sa.String(), nullable=True),
    sa.Column('avg_price', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('leaves_qty', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('leaves_value', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('cum_exec_qty', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('cum_exec_value', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('cum_exec_fee', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('stop_order_type', sa.String(), nullable=False),
    sa.Column('trigger_price', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('take_profit', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('stop_loss', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('tpsl_mode', sa.String(), nullable=True),
    sa.Column('last_price_on_created', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_orders_cancel_type'), 'orders', ['cancel_type'], unique=False)
    op.create_index(op.f('ix_orders_create_type'), 'orders', ['create_type'], unique=False)
    op.create_index(op.f('ix_orders_created_time'), 'orders', ['created_time'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_status'), 'orders', ['order_status'], unique=False)
    op.create_index(op.f('ix_orders_order_type'), 'orders', ['order_type'], unique=False)
    op.create_index(op.f('ix_orders_side'), 'orders', ['side'], unique=False)
    op.create_index(op.f('ix_orders_stop_order_type'), 'orders', ['stop_order_type'], unique=False)
    op.create_index(op.f('ix_orders_strategy_id'), 'orders', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_orders_tpsl_mode'), 'orders', ['tpsl_mode'], unique=False)
    op.create_index(op.f('ix_orders_updated_time'), 'orders', ['updated_time'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_updated_time'), table_name='orders')
    op.drop_index(op.f('ix_orders_tpsl_mode'), table_name='orders')
    op.drop_index(op.f('ix_orders_strategy_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_stop_order_type'), table_name='orders')
    op.drop_index(op.f('ix_orders_side'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_type'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_time'), table_name='orders')
    op.drop_index(op.f('ix_orders_create_type'), table_name='orders')
    op.drop_index(op.f('ix_orders_cancel_type'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
